In [ ]:
#### Submitted by: Ryan M. Vitalez

In [2]:
import numpy as np
from typing import Tuple

In [5]:
def gaussian_elimination(A: np.ndarray)-> Tuple[np.ndarray, np.ndarray]:
    
    B = np.copy(A).astype(float)
    num_rows, num_cols = B.shape
    
    pivot_columns = []
    pivot_rows = []
    
    row = 0
    col = 0
    
    while row < num_rows and col < num_cols:
        
        max_index = np.argmax(np.abs(B[row:num_rows, col])) + row
        
        if B[max_index, col] != 0:
            # swap rows
            B[[row, max_index]] = B[[max_index, row]]
            pivot_columns.append(col)
            pivot_rows.append(row)
            
            # scale the pivot rows
            B[row,:] /= B[row, col]
            
            # making sure that the entries below the pivot is zero
            for i in range(row + 1, num_rows):
                x = B[i, col]
                B[i, col:] -= x * B[row, col:]
                
            row += 1
        
        col += 1
    
    # column space
    C = A[:, pivot_columns]
    
    # row space
    R = B[pivot_rows, :]
    
    return C, R

In [6]:
# using the Homework #1 as example
A = np.array([
    [-2, 1, 3, 7],
    [-3, 0, 1, 0],
    [-2, -1, 0, -2]
])

C, R = gaussian_elimination(A)

print("Column Space, C:")
print(C)

print("Row Space, R:")
print(R)

Column Space, C:
[[-2  1  3]
 [-3  0  1]
 [-2 -1  0]]
Row Space, R:
[[ 1.         -0.         -0.33333333 -0.        ]
 [ 0.          1.          2.33333333  7.        ]
 [ 0.          0.          1.          3.        ]]


In [8]:
# using the Homework #1 as example
A = np.array([
    [-2, 1, 2],
    [0, -2, 2],
    [2, -3, 0],
    [6, -5, -4]
])

C, R = gaussian_elimination(A)

print("Column Space, C:")
print(C)

print("Row Space, R:")
print(R)


Column Space, C:
[[-2  1]
 [ 0 -2]
 [ 2 -3]
 [ 6 -5]]
Row Space, R:
[[ 1.         -0.83333333 -0.66666667]
 [-0.          1.         -1.        ]]
