In [1]:
import numpy as np

In [55]:
def householder_hessenberg(A): 
    A = np.array(A, 'float')
    m, n = A.shape
    H = np.copy(A)
    
    np.set_printoptions(suppress=True, precision=4)
    hist = {}
    
    for j in range(min(m, n) - 2):
        hist[j] = {}
        print(f'-----iter{j}-----')
        
        x = H[j + 1:, j]
        v = np.copy(x)
        v[0] += np.sign(x[0]) * np.linalg.norm(x)
        
        v = v / np.linalg.norm(v)
        H[j + 1:, j:] -= 2.0 * np.outer(v, np.dot(v, H[j + 1:, j:])).astype(np.float64)
        
        hist[j]['H'] = np.eye(n)
        hist[j]['H'][j + 1:, j + 1:] = np.eye(m - j -1) - 2.0 * np.outer(v, v)
        hist[j]['HAH'] = np.dot(hist[j]['H'], np.dot(H, hist[j]['H']))
        
        print(f'H\n{hist[j]["H"]}')
        print(f'HAH\n{hist[j]["HAH"]}')
        
    return hist

In [60]:
A1 = [
    [1, -2, 5],
    [6, 3, 9],
    [-1, 4, 8]
]

A2 = [
    [5, -2, 19, 6],
    [6, 22, 18, 2],
    [-1, 15, 8, -23],
    [14, 23, -38, 14]
]

A3 = [
    [10, 16, -5, 23, 35],
    [19, -31, 27, 15, 8],
    [-1, -17, 29, -4, 25],
    [9, -18, 7, 26, 33],
    [-18, 23, 38, -16, 5]
]


In [61]:
# 3x3 matrix, A1

result = householder_hessenberg(A1)

print(np.allclose(result[0]['HAH'], result[0]['HAH']))

-----iter0-----
H
[[ 1.      0.      0.    ]
 [ 0.     -0.9864  0.1644]
 [ 0.      0.1644  0.9864]]
HAH
[[ 1.      2.7948  4.6032]
 [ 6.     -1.4796  9.3707]
 [-1.     -2.6304  8.5487]]
True


In [62]:
# 4x4 matrix, A4

result = householder_hessenberg(A2)

print(np.allclose(result[0]['HAH'], result[0]['HAH']))

-----iter0-----
H
[[ 1.      0.      0.      0.    ]
 [ 0.     -0.3931  0.0655 -0.9172]
 [ 0.      0.0655  0.9969  0.0431]
 [ 0.     -0.9172  0.0431  0.3962]]
HAH
[[  5.      -3.4721  19.0692   5.0308]
 [  6.      -9.3027  19.4721 -18.6091]
 [ -1.      15.7229   7.966  -22.524 ]
 [ 14.     -24.3705 -35.7723 -17.1878]]
-----iter1-----
H
[[ 1.      0.      0.      0.    ]
 [ 0.      1.      0.      0.    ]
 [ 0.      0.     -0.8578  0.514 ]
 [ 0.      0.      0.514   0.8578]]
HAH
[[  5.      -2.     -13.2136  14.9131]
 [-15.2643 -28.7598 -32.055    1.5665]
 [ -0.      17.3871 -17.855  -15.1745]
 [ -0.     -10.4192  28.176  -13.7137]]
True


In [63]:
# 5x5 matrix, A3

result = householder_hessenberg(A3)

print(np.allclose(result[0]['HAH'], result[0]['HAH']))

-----iter0-----
H
[[ 1.      0.      0.      0.      0.    ]
 [ 0.     -0.6861  0.0361 -0.325   0.6499]
 [ 0.      0.0361  0.9992  0.007  -0.0139]
 [ 0.     -0.325   0.007   0.9374  0.1253]
 [ 0.      0.6499 -0.0139  0.1253  0.7495]]
HAH
[[ 10.       4.1163  -4.7455  20.7095  39.581 ]
 [ 19.      22.5674  25.8528  25.3246 -12.6493]
 [ -1.      30.2584  27.9879   5.1086   6.7827]
 [  9.      25.6005   6.0663  34.4036  16.1928]
 [-18.      -5.9578  38.6202 -21.5814  16.1627]]
-----iter1-----
H
[[ 1.      0.      0.      0.      0.    ]
 [ 0.      1.      0.      0.      0.    ]
 [ 0.      0.     -0.9458 -0.2057 -0.2513]
 [ 0.      0.     -0.2057  0.9782 -0.0266]
 [ 0.      0.     -0.2513 -0.0266  0.9675]]
HAH
[[ 10.      16.      -8.798   22.5984  34.5095]
 [-27.6948  41.4519   4.3766 -29.3438 -12.1337]
 [  0.     -18.5516 -33.637   -9.7245  17.2795]
 [  0.      -4.0355 -13.5144  15.7451  27.0333]
 [  0.      -4.9289 -47.4003  -8.8582   0.6061]]
-----iter2-----
H
[[ 1.      0.      0.   

In [ ]:
#### I referenced this code from the discussion last 25-03-2023.