In [1]:
import numpy as np

In [15]:
def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    for j in range(n):
        v = A[:, j] # initializes the vector, v
        for i in range(j):
            R[i, j] = np.dot(Q[:, i].T, A[:, j]) # taking the value of R by multiplying the Q transpose with original matrix A
            v = v - R[i, j] * Q[:, i] # subtracting the projection 
        R[j, j] = np.linalg.norm(v) # normalization of the set
        Q[:, j] = v / R[j, j] 
    
    return Q, R

def qr_decomposition(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    P = np.eye(n) 
    
    # column pivoting
    for j in range(n):
        col_norms = np.linalg.norm(A[:, j:], axis = 0)
        pivot_index = j + np.argmax(col_norms)
        A[:, [j, pivot_index]] = A[:, [pivot_index, j]]
        P[:, [j, pivot_index]] = P[:, [pivot_index, j]]
        
        Qj, Rj, = gram_schmidt(A[:, j:])
        Q[:, j:] = Qj
        R[j:, j:] = Rj
        
    return Q, R, P
        
        

In [24]:
A = np.array([
    [1, 2, 1],
    [1, -1, 1],
    [-1, 1, 1]
])

Q, R, P = qr_decomposition(A)

print("Orthogonal Matrix, Q:")
print("\n", Q)

print("\nUpper Triangular Matrix, R:")
print("\n", R)

Orthogonal Matrix, Q:

 [[ 0.81649658  0.57735027  0.57735027]
 [-0.40824829  0.57735027  0.57735027]
 [ 0.40824829 -0.57735027  0.57735027]]

Upper Triangular Matrix, R:

 [[2.44948974 0.         0.81649658]
 [0.         1.73205081 0.57735027]
 [0.         0.         1.73205081]]


In [25]:
A = np.array([
    [0.02, 1, 100],
    [0.04, 2, 45],
    [-0.01, 3, 16]
])

Q, R, P = qr_decomposition(A)

print("Orthogonal Matrix, Q:")
print("\n", Q)

print("\nUpper Triangular Matrix, R:")
print("\n", R)


Orthogonal Matrix, Q:

 [[ 0.90236685  0.26726124  0.43643578]
 [ 0.40606508  0.53452248  0.87287156]
 [ 0.1443787   0.80178373 -0.21821789]]

Upper Triangular Matrix, R:

 [[1.10819673e+02 2.14763311e+00 3.28461535e-02]
 [0.00000000e+00 3.74165739e+00 1.87082869e-02]
 [0.00000000e+00 0.00000000e+00 4.58257569e-02]]
