In [ ]:
#### Submitted by: Ryan M. Vitalez

#### Objective: Modify the Gaussian Elimination from Coding Challenge #1 and take into account the permutation matrix as well as the lower triangular matrix for LU decomposition.

In [1]:
import numpy as np
from typing import Tuple, List

In [2]:
def permutation_matrix(n: int, pivot_rows: List[int]) -> np.ndarray:
    P = np.eye(n)
    for i, row in enumerate(pivot_rows):
        P[[i, row], :] = P[[row, i], :]
    return P

In [3]:
def gaussian_elimination(A: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    B = np.copy(A).astype(float)
    num_rows, num_cols = B.shape
    
#    print("Original Matrix, A:")
#    print(A)
#    print()
    
    pivot_columns = []
    pivot_rows = []

    row = 0
    col = 0
    
    while row < num_rows and col < num_cols:
        max_index = np.argmax(np.abs(B[row:num_rows, col])) + row

        if B[max_index, col] != 0:
            
            B[[row, max_index]] = B[[max_index, row]]
            pivot_columns.append(col)
            pivot_rows.append(row)
            
            B[row+1:, col] /= B[row, col]
            
            for i in range(row + 1, num_rows):
                x = B[i, col]
                B[i, col:] -= x * B[row, col:]
                
            row += 1
        
        col += 1
              
#    print("Modified Matrix, B:")
#    print(B)
#    print()
    
    # lower triangular matrix
    L = np.eye(num_rows) + np.tril(B[:, :num_rows], k=-1)
    
    # upper triangular matrix (I think there is something wrong with this code I just can't figure out what)
    U = np.concatenate((B[:, :num_rows], B[:, num_rows:]), axis=1)
    
    # permutation matrix
    P = permutation_matrix(num_rows, pivot_rows)
    
    return  L, U, P
    

In [4]:
# using the given from Homework #1 as example
A = np.array([
    [-2, 1, 3, 7],
    [-3, 0, 1, 0],
    [-2, -1, 0, -2]
])
L, U, P = gaussian_elimination(A)

print("Lower Triangular Matrix, L:")
print(L)
print()

print("Upper Triangular Matrix, U")
print(U)
print()

print("Permutation Matrix, P:")
print(P)
    

Lower Triangular Matrix, L:
[[1.         0.         0.        ]
 [2.66666667 1.         0.        ]
 [2.66666667 0.         1.        ]]

Upper Triangular Matrix, U
[[-3.          0.          1.          0.        ]
 [ 2.66666667  1.          2.33333333  7.        ]
 [ 2.66666667  0.          1.66666667  5.        ]]

Permutation Matrix, P:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# to compute for the determinant of A

# in computing for the determinant, the given should be square matrix

def determinant(A: np.ndarray) -> float:
    L, U, P = gaussian_elimination(A)
    det = np.linalg.det(P) * np.prod(np.diag(U)) 
    return det

In [6]:
# using the given from Homework #1 as example
A = np.array([
    [-2, 1, 3, 7],
    [-3, 0, 1, 0],
    [-2, -1, 0, 2]
])

det_A = determinant(A)

print("Determinant of A:")
print(det_A)

Determinant of A:
-5.000000000000001


In [ ]:
### note: the result from determinant of A is not possible since in taking the determinant, you need to have a square matrix.